In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(
    r"C:\Users\ezhil\Downloads\spam.csv",
    encoding="latin1"
)

In [3]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [4]:
df = df[['v1','v2']]

df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df.columns = [
    "Label",
    "Message"
]

df.head()

  Label                                            Message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
df.shape

(5572, 2)

In [7]:
df.isnull().sum()

Label      0
Message    0
dtype: int64

In [8]:
df["Label"].value_counts()

Label
ham     4825
spam     747
Name: count, dtype: int64

In [9]:
df["Label"] = df["Label"].map({
    "ham":0,
    "spam":1
})

In [10]:
df.head()

   Label                                            Message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [11]:
X = df["Message"]

y = df["Label"]

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [13]:
vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(X)

In [14]:
X.shape

(5572, 8672)

In [17]:
df.head(X)

TypeError: cannot do positional indexing on RangeIndex with these indexers [<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 73916 stored elements and shape (5572, 8672)>
  Coords	Values
  (0, 3550)	0.1481298737377147
  (0, 8030)	0.22998520738984352
  (0, 4350)	0.3264252905795869
  (0, 5920)	0.2553151503985779
  (0, 2327)	0.25279391746019725
  (0, 1303)	0.24415547176756056
  (0, 5537)	0.15618023117358304
  (0, 4087)	0.10720385321563428
  (0, 1751)	0.2757654045621182
  (0, 3634)	0.1803175103691124
  (0, 8489)	0.22080132794235655
  (0, 4476)	0.2757654045621182
  (0, 1749)	0.3116082237740733
  (0, 2048)	0.2757654045621182
  (0, 7645)	0.15566431601878158
  (0, 3594)	0.15318864840197105
  (0, 1069)	0.3264252905795869
  (0, 8267)	0.18238655630689804
  (1, 5504)	0.27211951321382544
  (1, 4512)	0.4082988561907181
  (1, 4318)	0.5236458071582338
  (1, 8392)	0.4316010362639011
  (1, 5533)	0.5465881710238072
  (2, 4087)	0.07917128722158312
  (2, 3358)	0.11301399735581102
  :	:
  (5570, 4218)	0.12246610191126918
  (5570, 8313)	0.18723687600522523
  (5570, 1084)	0.11225268140936363
  (5570, 4615)	0.1596552981734164
  (5570, 7039)	0.18426763178390446
  (5570, 3308)	0.12172172618634511
  (5570, 7627)	0.10242646659763287
  (5570, 1438)	0.1429585509124154
  (5570, 5334)	0.21003730857873562
  (5570, 2592)	0.18458634504313887
  (5570, 8065)	0.2088086209859756
  (5570, 1778)	0.13664567516026058
  (5570, 7049)	0.205343868729306
  (5570, 2892)	0.2440099568063893
  (5570, 3470)	0.2752778321471702
  (5570, 1786)	0.28292057870729176
  (5570, 3687)	0.242516196245848
  (5570, 4161)	0.28292057870729176
  (5570, 903)	0.32476233976158125
  (5570, 1546)	0.340204888824892
  (5571, 7756)	0.14849350328973984
  (5571, 5244)	0.39009002726386227
  (5571, 4225)	0.5773238083586979
  (5571, 7885)	0.42752913176432156
  (5571, 6505)	0.5565029307246045] of type csr_matrix

In [18]:
df.head()

   Label                                            Message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [19]:
df.head(X[0])

TypeError: cannot do positional indexing on RangeIndex with these indexers [<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 18 stored elements and shape (1, 8672)>
  Coords	Values
  (0, 3550)	0.1481298737377147
  (0, 8030)	0.22998520738984352
  (0, 4350)	0.3264252905795869
  (0, 5920)	0.2553151503985779
  (0, 2327)	0.25279391746019725
  (0, 1303)	0.24415547176756056
  (0, 5537)	0.15618023117358304
  (0, 4087)	0.10720385321563428
  (0, 1751)	0.2757654045621182
  (0, 3634)	0.1803175103691124
  (0, 8489)	0.22080132794235655
  (0, 4476)	0.2757654045621182
  (0, 1749)	0.3116082237740733
  (0, 2048)	0.2757654045621182
  (0, 7645)	0.15566431601878158
  (0, 3594)	0.15318864840197105
  (0, 1069)	0.3264252905795869
  (0, 8267)	0.18238655630689804] of type csr_matrix

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [22]:
from sklearn.ensemble import RandomForestClassifier

In [23]:
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(
    X_train,
    y_train
)

RandomForestClassifier(random_state=42)

In [24]:
y_pred = model.predict(X_test)

In [25]:
from sklearn.metrics import accuracy_score

In [26]:
accuracy = accuracy_score(
    y_test,
    y_pred
)

print(
    "Accuracy:",
    accuracy
)

Accuracy: 0.9766816143497757

In [27]:
from sklearn.metrics import classification_report

In [28]:
print(
    classification_report(
        y_test,
        y_pred
    )
)

              precision    recall  f1-score   support

           0       0.97      1.00      0.99       965
           1       1.00      0.83      0.91       150

    accuracy                           0.98      1115
   macro avg       0.99      0.91      0.95      1115
weighted avg       0.98      0.98      0.98      1115

In [29]:
message = [
    "Congratulations! You won 50000 rupees. Click here now."
]

In [30]:
message_vector = vectorizer.transform(
    message
)

prediction = model.predict(
    message_vector
)

print(prediction)

[0]

In [31]:
print(df["Label"].value_counts())

Label
0    4825
1     747
Name: count, dtype: int64

In [32]:
print(prediction[0])

0

In [33]:
spam_msg = df[df["Label"] == 1]["Message"].iloc[0]

print(spam_msg)

Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's

In [34]:
spam_vector = vectorizer.transform(
    [spam_msg]
)

prediction = model.predict(
    spam_vector
)

print(prediction)

[1]

In [35]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(
    X_train,
    y_train
)

y_pred = model.predict(X_test)

In [36]:
from sklearn.metrics import accuracy_score

print(
    accuracy_score(
        y_test,
        y_pred
    )
)

0.9623318385650225

In [37]:
message = [
    "FREE entry into our weekly competition. WIN cash prize now!"
]

In [38]:
message_vector = vectorizer.transform(
    message
)

prediction = model.predict(
    message_vector
)

print(prediction)

[1]

In [39]:
from sklearn.metrics import confusion_matrix

print(
    confusion_matrix(
        y_test,
        y_pred
    )
)

[[965   0]
 [ 42 108]]

In [44]:
message = [
    "you can win the price amount if 20000 cash price free"
]

In [45]:
message_vector = vectorizer.transform(
    message
)

prediction = model.predict(
    message_vector
)

print(prediction)

[0]